# Generated by Django 2.0.1 on 2018-01-22 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pouet', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(verbose_name='date created')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='burnDownBackEnd.Company')),
            ],
        ),
    ]
