# Generated by Django 2.0.1 on 2018-01-22 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('burnDownBackEnd', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='pub_date',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='pub_date',
            new_name='create_date',
        ),
    ]
