# Generated by Django 2.0.1 on 2018-01-26 04:03

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('burnDownBackEnd', '0002_auto_20180121_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pbi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('snapshot_date', models.DateField(default=datetime.datetime.now, verbose_name='snapshot date')),
                ('storyPoints', models.PositiveIntegerField(default=0)),
                ('link', models.CharField(max_length=2048)),
                ('localId', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='PbiType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pbiType', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(default=None, verbose_name='start date')),
                ('end_date', models.DateField(default=None, verbose_name='end date')),
                ('goal', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='team',
            name='create_date',
        ),
        migrations.AddField(
            model_name='team',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date created'),
        ),
        migrations.AddField(
            model_name='sprint',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='burnDownBackEnd.Team'),
        ),
        migrations.AddField(
            model_name='pbi',
            name='pbitype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='burnDownBackEnd.PbiType'),
        ),
        migrations.AddField(
            model_name='pbi',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='burnDownBackEnd.State'),
        ),
    ]
