# Generated by Django 2.0.1 on 2018-01-31 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burnDownBackEnd', '0004_auto_20180125_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pbi',
            name='link',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='pbi',
            name='localId',
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='pbi',
            name='pbitype',
            field=models.CharField(choices=[('NEW', 'New'), ('ACTIVE', 'Active'), ('OPEN', 'Open'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], max_length=20),
        ),
    ]
