# Generated by Django 2.0.1 on 2018-02-01 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burnDownBackEnd', '0006_auto_20180130_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='pbi',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
