# Generated by Django 2.0.1 on 2018-02-04 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('burnDownBackEnd', '0007_pbi_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='pbi',
            name='sprint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='burnDownBackEnd.Sprint'),
        ),
    ]
