# Generated by Django 2.0.1 on 2018-02-21 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burnDownBackEnd', '0008_pbi_sprint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pbi',
            old_name='localId',
            new_name='local_id',
        ),
        migrations.RenameField(
            model_name='pbi',
            old_name='pbitype',
            new_name='pbi_type',
        ),
        migrations.RenameField(
            model_name='pbi',
            old_name='storyPoints',
            new_name='story_points',
        ),
        migrations.AddField(
            model_name='pbi',
            name='area',
            field=models.CharField(default='', max_length=2048),
        ),
        migrations.AddField(
            model_name='pbi',
            name='is_interuption',
            field=models.BooleanField(default=False),
        ),
    ]
