# Generated by Django 2.0.1 on 2018-02-23 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burnDownBackEnd', '0010_auto_20180220_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pbi',
            name='story_points',
            field=models.FloatField(default=0),
        ),
    ]
