# Generated by Django 2.0.1 on 2018-07-24 01:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burnDownBackEnd', '0011_auto_20180222_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 23, 21, 24, 24, 590295), verbose_name='date created'),
        ),
    ]
